name: Create PDF release from markdown

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir .old &&
          rsync -vr ./* .old/ --exclude .old &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/ABWL-LEDER/README.md > ABWL-LEDER/README.md &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/ASM-GUENTHER/README.md > ASM-GUENTHER/README.md &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/DBS-DORENDORF/README.md > DBS-DORENDORF/README.md &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/PRO-KASCHE/README.md > PRO-KASCHE/README.md &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/SWE-KASCHE/README.md > SWE-KASCHE/README.md &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/OOP-CASSELT/README.md > OOP-CASSELT/README.md &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/SWS-KUSCHE/README.md > SWS-KUSCHE/README.md &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/MPP-PI/README.md > MPP-PI/README.md
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/MPP-PI/Fragenkatalog-Vorgaenger.md > MPP-PI/Fragenkatalog-Vorgaenger.md

      - run: |
          mkdir output
      - uses: docker://rstropek/pandoc-latex:latest # generate ABWL-LEDER pdf
        with:
          args: --output=output/ABWL-LEDER.pdf --resource-path=ABWL-LEDER/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.0.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose ABWL-LEDER/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate ASM-GUENTHER pdf
        with:
          args: --output=output/ASM-GUENTHER.pdf --resource-path=ASM-GUENTHER/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.0.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose ASM-GUENTHER/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate DBS-DORENDORF pdf
        with:
          args: --output=output/DBS-DORENDORF.pdf --resource-path=DBS-DORENDORF/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.0.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose DBS-DORENDORF/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate PRO-KASCHE pdf
        with:
          args: --output=output/PRO-KASCHE.pdf --resource-path=PRO-KASCHE/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.0.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose PRO-KASCHE/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate SWE-KASCHE pdf
        with:
          args: --output=output/SWE-KASCHE.pdf --resource-path=SWE-KASCHE/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.0.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose SWE-KASCHE/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate SWE-KASCHE pdf
        with:
          args: --output=output/SWS-KUSCHE.pdf --resource-path=SWS-KUSCHE/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.0.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose SWS-KUSCHE/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate OOP-CASSELT pdf
        with:
          args: --output=output/OOP-CASSELT.pdf --resource-path=OOP-CASSELT/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.0.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose OOP-CASSELT/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate MPP-PI pdf
        with:
          args: --output=output/MPP-PI.pdf --resource-path=MPP-PI/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.0.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose MPP-PI/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate MPP-PI/Fragenkatalog-Vorgaenger.md
        with:
          args: --output=output/MPP-Fragenkatalog-Vorgaenger.pdf --resource-path=MPP-PI/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.0.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose MPP-PI/Fragenkatalog-Vorgaenger.md
      - uses: actions/upload-artifact@master # upload pdfs as an artifact
        with:
          name: output
          path: output
 release_pdfs:
    runs-on: ubuntu-20.04
    needs: convert_via_pandoc
    if: github.ref == 'refs/heads/main' # only publish if commited to the main branch
    steps:
      - name: Retrieve saved Docker image
        uses: actions/download-artifact@v2
        with:
          name: output
          path: output
      - uses: meeDamian/github-release@2.0
	      with:
	        token: ${{ secrets.GITHUB_TOKEN }}
          tag: pdf-release
          name: PDFs
          body: Dieses Release wurde automatisch erstellt
          gzip: false
          files: output/*.pdf
          allow_override: true
